name: macOS arm64 Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up CMake
      uses: lukka/get-cmake@latest
      
    - name: Build HarfBuzz for macOS arm64
      run: |
        # Set up compiler flags for arm64
        export CFLAGS="-arch arm64 -isysroot $(xcrun --sdk macosx --show-sdk-path)"
        export CXXFLAGS="-arch arm64 -isysroot $(xcrun --sdk macosx --show-sdk-path)"
        export LDFLAGS="-arch arm64"
        
        # Create build and install directories
        mkdir -p build/macos-arm64
        mkdir -p libs/macos-arm64
        
        # Build HarfBuzz
        cd build/macos-arm64
        
        cmake ../../src/harfbuzz \
          -DCMAKE_OSX_ARCHITECTURES="arm64" \
          -DCMAKE_BUILD_TYPE=Release \
          -DHB_HAVE_FREETYPE=OFF \
          -DHB_HAVE_GLIB=OFF \
          -DHB_HAVE_ICU=OFF \
          -DHB_HAVE_GRAPHITE2=OFF \
          -DHB_HAVE_CORETEXT=ON \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_MACOSX_RPATH=ON \
          -DBUILD_FRAMEWORK=OFF \
          -DCMAKE_INSTALL_PREFIX="../../libs/macos-arm64"
        
        cmake --build . --config Release
        cmake --install .
        
        # Verify the architecture of the built libraries
        echo "Verifying library architecture..."
        for lib in ../../libs/macos-arm64/lib/*.a; do
          if [ -f "$lib" ]; then
            echo "Checking: $lib"
            lipo -info "$lib"
          fi
        done
        
    - name: Upload built libraries
      uses: actions/upload-artifact@v4
      with:
        name: harfbuzz-macos-arm64
        path: libs/macos-arm64/
